[build]
  base = "katana-ai-nexus-portfolio"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "katana-ai-nexus-portfolio/dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  RUBY_VERSION = "3.2.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 